input_file: ../database/sample1.dng
output_file: pipeline_with_exposure_output.jpg
pipeline:
- module: exposure
  enabled: false
  params:
    exposure_ev: 0.5
    black_level: 0.01
- module: whitebalance
  enabled: true
  params:
    temp_k: 6502.0
    tint: 1.0
- module: filmicrgb
  enabled: false
  params:
    white_point_ev: 3.0
    black_point_ev: -8.0
    contrast: 1.2
    latitude: 0.4
    preserve_color: luminance
- module: colorbalancergb
  enabled: false
  params:
    shadows_H: 0.0
    shadows_C: 0.05
    shadows_Y: 0.0
    midtones_H: 0.0
    midtones_C: 0.0
    midtones_Y: 0.0
    highlights_H: 0.0
    highlights_C: 0.05
    highlights_Y: 0.0
    contrast: 0.05
    grey_fulcrum: 0.1845
    white_fulcrum: 0.0
    vibrance: 0.1
    chroma_global: 0.0
    chroma_shadows: 0.0
    chroma_midtones: 0.0
    chroma_highlights: 0.0
    mask_grey_fulcrum: 0.1845
    shadows_weight: 1.0
    highlights_weight: 1.0
    global_H: 0.0
    global_C: 0.0
    global_Y: 0.0
    hue_angle: 0.0
- module: soften
  enabled: false
  params:
    size: 40.0
    brightness: 0.6
    saturation: 100.0
    amount: 65.0
- module: diffuse
  enabled: false
  params:
    iterations: 20.0
    speed: 0.5
    anisotropy: 0.9
    edge_sensitivity: 0.02
- module: bloom
  enabled: false
  params:
    strength: 1.0
    radius: 0.02
    threshold: 90.0
- module: borders
  enabled: false
  params:
    size: 0.05
    color: '[255, 255, 255]'
- module: watermark
  enabled: false
  params:
    watermark_file: darktable_python/assets/logo_Hour.png
    scale: 0.15
    opacity: 0.2
    position: bottom-right
- module: vignette
  enabled: false
  params:
    strength: 0.8
    radius: 0.9
    softness: 1.0
- module: grain
  enabled: false
  params:
    strength: 0.8
    coarseness: 0.8
- module: highpass
  enabled: false
  params:
    radius: 10.0
    contrast: 1.0
- module: sharpen
  enabled: false
  params:
    radius: 2.0
    amount: 5.0
- module: blurs
  enabled: false
  params:
    blur_type: motion
    radius: 10.0
    blades: 6.0
    concavity: 1.0
    linearity: 1.0
    rotation: 0.0
    angle: 0.0
    curvature: 0.0
    offset: 0.0
- module: dither
  enabled: false
  params:
    method: posterize
    levels: 4.0
- module: lowlight
  enabled: false
  params:
    blueness: 50.0
    curve_points: '[[0.0, 0.0], [0.5, 0.2], [1.0, 1.0]]'
- module: invert
  enabled: false
  params: {}
